### ISSUE TITLE
Fix learn more link on science 360 recruiter - it's currently 404ing

### ISSUE THREAD

**Issue by line47** [GSA/recruiter#33]
The URL for the `Learn more` link in the recruiter popup should go to https://www.nsf.gov/web-design-labs/. Currently it is going to https://science360.gov/web-design-labs/ which is a 404

**Comment by laurenancona** [comment]
Fixed in [GTM Version 19](https://tagmanager.google.com/#/versions/accounts/1357356891/containers/7386222/versions/19)

Description:
> This update makes explicit the nsf.gov domain to avoid 404-ing links when recruiter loads on other NSF domains, such as science360.gov.
It also removes an unused tag: load-recruiter-tab-only.js that was initially intended to service science360.gov
